### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by RYXN2003** [xBrooky/CMP1903M-Assessment-1-Base-Code#1]
### What does the code do well?

Overall the commenting across all classes of the program is done effectively making the code relatively easy to understand from the perspective of a different programmer. The code is also structured so that everything in the program looks neat and tidy, this will contribute towards the codes readability.  The majority of the variable names across the program are clearly defined meaning that the person reading the code has a clear idea of what each variables' purpose is.  The general error handling is very good since it allows any exceptions such as the user not entering a valid response to the input choice, this helps to avoid the console application from ending prematurely. On top of this the program has successfully implemented all of the required functionality which shows that the program as a whole consists of efficient and effective code.

### Potential improvements

There are few improvements that can be made to the code in this program. One of the few faults I picked up on was the commenting in certain places can be either a bit too little in order to understand what's going on or too much commenting which may be unnecessary such as in INPUT.cs (lines 29-42). The only other thing I picked up on was the method used to report the values to the console, this method might seem over complicated and the overall tidiness of the code may look better if a shorter but still effective method is used.

**Comment by xBrooky** [comment]
Thank you for the feedback, i will amend the suggested changes
