### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by v-Zak** [xBrooky/CMP1903M-Assessment-1-Base-Code#2]
### **Code Review** 

**1. is the code properly documented/commented?** 

In many places the code is exceptionally well documented and fully commented an example of this is in the analyse class where the function analyseText() has a complete description of what it does including the expected inputs and outputs of the function. If everywhere in the code was as well commented as this then the code would be very readable and easy to debug. However, in some areas there is limited to no comments given at all, I believe this is because the code is still under development but for future ensure code is commented fully before having it reviewed so the reviewer knows what you think the block of code should actually be doing. 

The code variable names and method names are also great, sticking to a consistent naming convention. Some names could be improved to make it clearer what they do an example is the objects instantiated at the top of the program.cs. For example, the object inputText implies it’s a string but it’s the object that fetched the string, therefore call it something like inputManager. 

The following areas are examples where comments would help to achieve a consistent standard: 

Analyse.cs 

Line 29-32 – explain why two files are created 

Line 35 – 39 – comment is good but remove “could indicate” in favour of “* does indicate” your telling someone what it does so don’t doubt yourself! 

Line 80 – // only analyse until the end character (*) is found 

Line 88-100 – more line by line comments I.e “create a list of words, if any words are longer than 7 write to a fil of long words” 

Input.cs 

Line 10 – add description on the purpose of the class like in analyse.cs 

Line 11-22 – comment purpose of each code block I.e. “enumerator to store the valid input options” 

Lines 44 – 55 – more line-by-line comments needed 

Line 58 - method has no description above it 

Line 65 –68 // get input from command line and try to return option as an int 

Line 79 – 84 - // get the path from the user and return the text from the file specifies 

Line 88 // if the fil is not found tell the user and ask them to enter another path 

If you then comment the rest of the classes using these 2 as an example you will have an extremely well documented project. While going through also ensure all the variable names makes sense. One way to think of it is that you’ve got to know what that variable is without having to look elsewhere for it. A perfect example of a good variable name is charsToRemove found in the analyse.cs line 57. 

**2. Does the code handle errors properly?** 

The code shows promising attempts at error handling namely the try catch in the input.cs - fileTextInput() method. This try catch would catch any errors made when entering the file path. This basic error catching works and allows the program to continue running. This concept should be used whenever there is an interaction between the program and any external factors. The user could be anything that you aren’t in 100% sure of I.e., that the user will enter a number or whether a file will actually exist. These interactions should all be handled with error handling to ensure the program always runs and exits gracefully. For even greater clarity you could try implement multiple catches per try statement. This is beneficial as it allows you to customize how you want to fix an error on a more case by case basis. A good example of which can be found here: 

https://docs.microsoft.com/en-us/dotnet/standard/io/handling-io-errors 

This example may be a bit overkill but shows how you can chain multiple catches allowing tighter control of the program's execution. If in doubt try to break your program, when the program beaks take note of the error and make a catch to deal with that error. 

**3. Suggestions for improvement:** 

The code is almost there with many things fully functioning like the sentence count, lowercase count and vowel count. Areas for improvement are as follows: 

Fixing analysis – your analyseText method currently contains blocks of code which belong in other classes. For example, line 29-33 and line 95 – 96 deal with input and output. The inputs should all be grouped into input.cs and wrapped in functions so they can be called elsewhere. The same goes for outputs these should be put in the report.cs file. The purpose of the analyse class is to handle the analysis not anything else. All the classes should be called in the main program.cs file and return their values. So in the case of analyse.cs the methods should return the variables calculated which then should be passed into the report.cs object for output. Think of the below example: 

 

//First create all the separate classes and their methods 

Class input 

Method getManualInput: 

Read input from command line 

Return the input 

 

Class analyse 

Method analyseText: 

Take in a string and return a list 

//This list contains number of sentences, number of vowels etc. 

 

Class report 

Method printList: 

Receive a list and print out the contents of the list in a formatted way 

 

//Then in the main program class 

Class program 

Method Main: 

//Create each object 

inputManager = new input
//do for all 3 classes
… 
...

//Then call each class as needed and store / pass on the variables 

input = inputManager.getManualInput() 

Result = analyseManager.analyseText(input) 

reportManger.printList(result) 

 

The following pseudocode would tackle in an input analyse it and output the result back out. Each class has one purpose / niche which it completely handles. All the passing of variables between classes Then happens in the main program.cs file. 

In order to fix the rest of your analysis its mostly logic errors. Take the way you calculate consonants the idea that consonants are just all the character that are not vowels is correct. However, if you look at the current logic of the below example: 

Bool of the following expressions: 

(not a) or (not b) 

This expression will return true no matter what. For example, if a is entered: 

False or true = true 

But what we actually want to check is whether the input is not either of them: 

Not (a or b) 

This expression now evaluates to false if a is entered: 

Not (true) = false 

Therefore in your code the statement should be  

!(lowerCaseInput[I] = “a” || lowerCaseInput[I] = “e” || ….) 

A nicer way of writing this however is simply by putting an else instead of the if statement. As if the first statement isn’t true (the character is a vowel) then it must be a consonant. Note this only works as you’ve removed all other characters except the letters. Also since the input is all lowercase the char does not need to be compared with any of the uppercase vowels I.e. A or E.  

Overall, a good start on the project showing signs of promise. Don’t be put off by the above improvements as it’s impossible to improve wihtout making mistakes. I understand the improvements have only covered the analysis.cs file but I feel the above review is probably already overwhelming enough without listing any further improvement. Hopefully by fixing the above issues you will be able to apply what you have learnt to the other classes.  

**4. Summary:**

If you want any clarity on the above issues feel free to contact me. Also, don’t hesitate if you get stuck on other areas of the code like the input as there are a few errors I have found but not mentioned in the above review. 

Most Importantly keep it up! Trust me it gets easier the more you code!

**Comment by xBrooky** [comment]
Thank you for the feedback! I will amend the suggested changes
